Repository streamplace/streamplace, pull requests merged in 2025-09, with the labels that each got.

#529 chat: scroll up to dismiss keyboard
  js/app/components/mobile/chat.tsx
  js/components/src/components/chat/chat.tsx
Labels: enhancement

#546 login: few small tweaks
  js/app/components/login/login.tsx
  js/app/components/login/signup.tsx
  js/app/src/router.tsx
Labels: enhancement

#542 player: store global volume state
  js/app/components/mobile/desktop-ui/mute-overlay.tsx
  js/app/components/mobile/desktop-ui/volume-slider.tsx
  js/app/components/mobile/ui.tsx
  js/app/features/base/baseSlice.tsx
  js/app/features/base/sidebarSlice.tsx
  js/app/features/bluesky/blueskySlice.tsx
  js/app/features/streamplace/streamplaceSlice.tsx
  js/app/store/listener.ts
  js/components/package.json
  js/components/src/components/mobile-player/ui/autoplay-button.tsx
  js/components/src/components/mobile-player/video-async.native.tsx
  js/components/src/components/mobile-player/video.tsx
  js/components/src/index.tsx
  js/components/src/player-store/player-state.tsx
  js/components/src/player-store/player-store.tsx
  js/components/src/storage/index.tsx
  js/components/src/storage/lock.tsx
  js/components/src/storage/storage.native.tsx
  js/components/src/storage/storage.shared.tsx
  js/components/src/storage/storage.tsx
  js/components/src/streamplace-store/streamplace-store.tsx
  js/components/tsconfig.json
  pnpm-lock.yaml
Labels: enhancement

#541 discord: add webhook interface and save to pg
  js/app/components/settings/settings.tsx
  js/app/components/settings/webhook-manager.tsx
  js/docs/src/content/docs/guides/start-streaming/discord-hooks.md
  js/docs/src/content/docs/lex-reference/openapi.json
  js/docs/src/content/docs/lex-reference/server/place-stream-server-createwebhook.md
  js/docs/src/content/docs/lex-reference/server/place-stream-server-defs.md
  js/docs/src/content/docs/lex-reference/server/place-stream-server-deletewebhook.md
  js/docs/src/content/docs/lex-reference/server/place-stream-server-getwebhook.md
  js/docs/src/content/docs/lex-reference/server/place-stream-server-listwebhooks.md
  js/docs/src/content/docs/lex-reference/server/place-stream-server-updatewebhook.md
  lexicons/place/stream/server/createWebhook.json
  lexicons/place/stream/server/defs.json
  lexicons/place/stream/server/deleteWebhook.json
  lexicons/place/stream/server/getWebhook.json
  lexicons/place/stream/server/listWebhooks.json
  lexicons/place/stream/server/updateWebhook.json
  pkg/integrations/discord/avatars.go
  pkg/integrations/discord/send-chat.go
  pkg/integrations/discord/send-livestream.go
  pkg/integrations/webhook/manager.go
  pkg/spxrpc/stubs.go
  pkg/spxrpc/webhook.go
  pkg/statedb/queue_processor.go
  pkg/statedb/statedb.go
  pkg/statedb/statedb_test.go
  pkg/statedb/webhook.go
  pkg/statedb/webhook_test.go
  pkg/streamplace/servercreateWebhook.go
  pkg/streamplace/serverdefs.go
  pkg/streamplace/serverdeleteWebhook.go
  pkg/streamplace/servergetWebhook.go
  pkg/streamplace/serverlistWebhooks.go
  pkg/streamplace/serverupdateWebhook.go
Labels: enhancement

#606 fix: set max lines for livestream title from 1 to 3
  js/app/components/mobile/bottom-metadata.tsx
Labels: bug

#604 ui: remove tamagui fixes 2
  js/app/components/mobile/chat.tsx
  js/app/components/mobile/player.tsx
  js/app/components/mobile/ui.tsx
  js/app/components/provider/provider.shared.tsx
  js/app/src/router.tsx
  js/components/src/components/ui/primitives/modal.tsx
Labels: tech debt

#605 fix: proxy com.atproto.repo.* correctly
  pkg/spxrpc/com_atproto_repo.go
  pkg/spxrpc/spxrpc.go
Labels: bug

#619 feat: make the Stream Key display less suck
  js/app/components/live-dashboard/stream-key.tsx
Labels: enhancement
