Repository streamplace/streamplace, pull requests merged in 2025-05, with the labels that each got.

#140 docs: add some links to docs
  LICENSE
  README.md
  js/app/src/router.tsx
  js/docs/src/content/docs/guides/start-contributing/streaming-in-development.md
  js/docs/src/content/docs/guides/start-contributing/streamplace-dev-setup.md
Labels: documentation

#134 app: minor ui fixes
  js/app/components/chat/chat-box.tsx
  js/app/components/chat/chat.tsx
  js/app/components/settings/settings.tsx
  js/app/src/router.tsx
Labels: enhancement

#139 make sure ../atproto is present
  .ci/dockerfile-hash.yaml
  .github/workflows/build.yaml
  .gitlab-ci.yml
  Makefile
  docker/build.Dockerfile
  meson.build
  subprojects/.gitignore
  subprojects/atproto.wrap
  subprojects/packagefiles/atproto/meson.build
Labels: bug

#131 app: add user follow on stream page
  js/app/components/follow-button.tsx
  js/app/components/livestream/livestream.tsx
  js/app/features/bluesky/blueskySlice.tsx
  js/docs/src/content/docs/lex-reference/graph/place-stream-graph-getfollowinguser.md
  lexicons/place/stream/graph/getFollowingUser.json
  pkg/model/follow.go
  pkg/model/model.go
  pkg/spxrpc/graph.go
  pkg/spxrpc/stubs.go
  pkg/streamplace/graphgetFollowingUser.go
Labels: enhancement

#162 fIx: remove key on navigator
  js/app/src/router.tsx
Labels: bug

#166 app: fix native fullscreen view
  js/app/components/livestream/livestream.tsx
  js/app/contexts/FullscreenContext.tsx
  js/app/src/screens/stream.tsx
Labels: enhancement

#165 adds a counting timer to the livestream info bar?\
  js/app/components/livestream/livestream.tsx
  js/app/components/timer.tsx
Labels: enhancement

#153 app: custom live thumbnail + client-side thumbnail generation
  js/app/components/create-livestream.tsx
  js/app/components/player/fullscreen.native.tsx
  js/app/components/player/fullscreen.tsx
  js/app/components/player/player.tsx
  js/app/components/player/props.tsx
  js/app/components/player/video.native.tsx
  js/app/components/player/video.tsx
  js/app/components/thumbnail-selector/index.tsx
  js/app/components/thumbnail-selector/shared.tsx
  js/app/components/thumbnail-selector/thumbnail-selector.native.tsx
  js/app/components/thumbnail-selector/thumbnail-selector.tsx
  js/app/contexts/VideoElementContext.tsx
  js/app/features/bluesky/blueskySlice.tsx
  js/app/hooks/useCaptureVideoFrame.ts
  js/app/src/screens/live-dashboard.tsx
  js/app/utils/videoCapture.ts
Labels: enhancement

#169 fix: completely hide sidebar on change to fullscreen
  js/app/components/player/fullscreen.native.tsx
  js/app/components/sidebar/sidebar-item.tsx
  js/app/components/sidebar/sidebar.tsx
  js/app/contexts/FullscreenContext.tsx
  js/app/features/base/sidebarSlice.tsx
  js/app/hooks/useSidebarControl.tsx
  js/app/src/router.tsx
Labels: enhancement

#187 xrpc: add feed error handling
  pkg/api/api.go
  pkg/oproxy/oauth_middleware.go
  pkg/spxrpc/app_bsky_feed.go
  pkg/spxrpc/spxrpc.go
Labels: enhancement

#170 design: redo home menu
  .yarn/patches/@atproto-oauth-client-npm-0.3.16-f0e37a9473.patch
  js/app/assets/images/goose.png
  js/app/assets/images/jelly.png
  js/app/components/container.tsx
  js/app/components/debug/breakpoint-indicator.tsx
  js/app/components/home/avatar.tsx
  js/app/components/home/cards.tsx
  js/app/components/home/live-dot.tsx
  js/app/components/stream-list/stream-list.tsx
  js/app/components/title.tsx
  js/app/features/bluesky/blueskySlice.tsx
  js/app/features/bluesky/blueskyTypes.tsx
  js/app/features/streamplace/streamplaceSlice.tsx
  js/app/hooks/useAvatars.tsx
  js/app/hooks/useSidebarControl.tsx
  js/app/package.json
  js/app/src/router.tsx
  js/app/src/screens/home.tsx
  js/app/tamagui.config.ts
  js/atproto-oauth-client-react-native/package.json
  js/docs/src/content/docs/lex-reference/live/place-stream-live-getliveusers.md
  js/docs/src/content/docs/lex-reference/place-stream-livestream.md
  lexicons/place/stream/live/getLiveUsers.json
  lexicons/place/stream/livestream.json
  package.json
  pkg/api/api.go
  pkg/model/livestream.go
  pkg/model/model.go
  pkg/spxrpc/place_stream_live.go
  pkg/spxrpc/stubs.go
  pkg/streamplace/livegetLiveUsers.go
  pkg/streamplace/streamlivestream.go
  yarn.lock
Labels: enhancement

#189 golive: update title option
  js/app/components/edit-livestream.tsx
  js/app/components/player/props.tsx
  js/app/components/player/provider.tsx
  js/app/components/ui/button-selector.tsx
  js/app/features/bluesky/blueskySlice.tsx
  js/app/src/screens/live-dashboard.tsx
  pkg/atproto/atproto.go
  pkg/atproto/firehose.go
  pkg/atproto/sync.go
Labels: enhancement

#212 docs: openapi gen with lexmd
  Makefile
  js/docs/astro.config.mjs
  js/docs/package.json
  js/docs/src/content/docs/lex-reference/openapi.json
  package.json
  pnpm-lock.yaml
Labels: documentation
