Repository streamplace/streamplace, pull requests merged in 2025-08, with the labels that each got.

#443 docs: main docs are a bit wider on >lg displays
  js/docs/astro.config.mjs
  js/docs/src/styles/widths.css
Labels: documentation

#456 statedb: migrate to a stateful database for stateful things
  .vscode/launch.json
  go.mod
  go.sum
  pkg/api/api.go
  pkg/api/api_internal.go
  pkg/atproto/firehose.go
  pkg/atproto/jwks.go
  pkg/atproto/lexicon_repo.go
  pkg/atproto/lexicon_repo_test.go
  pkg/atproto/sync.go
  pkg/cmd/streamplace.go
  pkg/config/config.go
  pkg/director/director.go
  pkg/director/stream_session.go
  pkg/integrations/discord/avatars.go
  pkg/integrations/discord/send-chat.go
  pkg/integrations/discord/send-livestream.go
  pkg/media/media_test.go
  pkg/model/model.go
  pkg/model/notification.go
  pkg/model/oauth_session.go
  pkg/resync/resync.go
  pkg/spxrpc/com_atproto_sync.go
  pkg/spxrpc/spxrpc.go
  pkg/statedb/config.go
  pkg/statedb/jwks.go
  pkg/statedb/locks.go
  pkg/statedb/migrate.go
  pkg/statedb/notification.go
  pkg/statedb/oauth_session.go
  pkg/statedb/queue_processor.go
  pkg/statedb/statedb.go
  pkg/statedb/task.go
  pkg/statedb/xrpc_stream_event.go
Labels: bug, tech debt

#517 player: add play button if we can't autoplay on web
  js/app/components/mobile/desktop-ui.tsx
  js/app/components/mobile/ui.tsx
  js/components/src/components/mobile-player/fullscreen.tsx
  js/components/src/components/mobile-player/ui/autoplay-button.tsx
  js/components/src/components/mobile-player/ui/index.ts
  js/components/src/components/mobile-player/video.tsx
  js/components/src/player-store/player-state.tsx
  js/components/src/player-store/player-store.tsx
Labels: enhancement

#518 chat: filter out system "users" from handle recommendations
  js/components/src/components/chat/chat-box.tsx
Labels: enhancement
